// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg-kiAs2QjBW2zuMXwHFrwzJPA6B_94IU',
    appId: '1:1097284291563:web:8b2fcd65805ae2abdb67ae',
    messagingSenderId: '1097284291563',
    projectId: 'codelab-9d241',
    authDomain: 'codelab-9d241.firebaseapp.com',
    storageBucket: 'codelab-9d241.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDq93mD7V5OQg94LW0-zvCzVuktb0wYbc',
    appId: '1:1097284291563:android:fb1b0fa9d42684acdb67ae',
    messagingSenderId: '1097284291563',
    projectId: 'codelab-9d241',
    storageBucket: 'codelab-9d241.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy7T03hSF8WryBtxzrIrPLFGjV5r7S6Yk',
    appId: '1:1097284291563:ios:8fc945a16c183759db67ae',
    messagingSenderId: '1097284291563',
    projectId: 'codelab-9d241',
    storageBucket: 'codelab-9d241.appspot.com',
    iosBundleId: 'com.example.firebaseAuthLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy7T03hSF8WryBtxzrIrPLFGjV5r7S6Yk',
    appId: '1:1097284291563:ios:8fc945a16c183759db67ae',
    messagingSenderId: '1097284291563',
    projectId: 'codelab-9d241',
    storageBucket: 'codelab-9d241.appspot.com',
    iosBundleId: 'com.example.firebaseAuthLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg-kiAs2QjBW2zuMXwHFrwzJPA6B_94IU',
    appId: '1:1097284291563:web:daf9961ddae39231db67ae',
    messagingSenderId: '1097284291563',
    projectId: 'codelab-9d241',
    authDomain: 'codelab-9d241.firebaseapp.com',
    storageBucket: 'codelab-9d241.appspot.com',
  );
}
